name:  First Workflow
on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: |
          echo "Hello, World!"
          echo "This is a simple workflow to run shell commands."
          echo "You can add more commands here as needed."

  parallel-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Run multiple commands in parallel
        run: |
          echo "Running command 1"
          sleep 5
          echo "Command 1 completed"

  