name: dependflow
on:
    workflow_run:
        workflows: ["simple-action", "checkout", "manual"]
        types: [completed]

jobs:
    echo-string:
        runs-on: ubuntu-latest
        steps:
           - run: echo "This workflow runs after the completion of simple-action, checkout, and manual workflows."