name: Expressions & Context
on: [push, pull_request, workflow_dispatch,issues]
run-name: "Expressions & contexts by ${{ github.actor }}"
jobs:
    using-expressions:
        runs-on: ubuntu-latest
        if: ${{ github.event_name == 'push' }}
        steps:
          - name: Using expressions
            run: |
                echo ${{ 1 }}
                echo ${{ 'This is a string' }}
                echo ${{ true }}
                echo ${{ false }}
                echo ${{ null }}
                echo ${{ 1 < 2}}
                echo ${{ 'string' == 'String'}}
                echo ${{ true && false}}
                echo ${{ secrets.GITHUB_TOKEN }}
