name: FirstWorkflow
on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        

        run: |
          echo "Hello, World!"
          echo "This is a simple workflow to run shell commands."
          echo "You can add more commands here as needed."
  run-python-script:
    needs: run-shell-commands
    runs-on: ubuntu-latest
    step:
      - name: Run a Python script
        run: |
          echo "Running a Python script..."
          python -c "print('Hello from Python!')"
          python -c "for i in range(5): print(f'Count: {i}')"