name: Matrix
on: [push]

jobs:
  node-matrix:
    strategy:
      matrix:
        node-version: [14, 16, 18]
        os: [ubuntu-latest, windows-latest]
        exclude:
          - node-version: 14
            os: windows-latest
      max-parallel: 4
    runs-on: ${{ matrix.os }}
    steps:
      - run: node -v
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: node -v