name: Matrix
on: [push]

jobs:
  node-matrix:
    continue-on-error: ${{ matrix.experimental == true}}
    strategy:
      matrix:
        node-version: [14, 16, 18]
        os: [ubuntu-latest, windows-latest]
        
        include:
          - os: ubuntu-latest
            is-ubuntu: true
            node-version: 16
          - experimental: true
          - os: ubuntu-latest
            node-version: 17
            experimental: false
          
        exclude:
          - node-version: 14
            os: windows-latest
            
      fail-fast: true
      max-parallel: 4
    runs-on: ${{ matrix.os }}
    steps:
      - if: matrix.experimental ==  false
        run: exit 1
      - run: node -v

      - run: echo '${{toJson(matrix)}}'
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: node -v
      - run: echo '${{toJson(matrix)}}'
        