name: Stale Issues & PRs
on:
  schedule:
    - cron: "20 16 * * *" # Runs daily at midnight
    - cron: "0/5 * * * *" # Runs every 5 minutes
jobs:
    stale:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/stale@v8
            with:
              repo-token: ${{ secrets.GITHUB_TOKEN }}
              days-before-stale: 30
              days-before-close: 7
