name: Variables and Secrets
on: [push]

jobs:
    log-vars:
        runs-on: ${{vars.JOBS_RUNNER}}
        env:
            BOOLEAN_SECRET: ${{ secrets.REPO_LEVEL_SECRET }}
            ENV_LEVEL_VAR: ${{ vars.ENV_LEVEL_VAR }}
            REPO_LEVEL_VAR: ${{ vars.REPO_LEVEL_VAR }}
        steps:
            - name: RUN Only if BOOLEAN SECRET is true
              if: env.REPO_LEVEL_SECRET == 'true'
              run: echo "This step runs only if the BOOLEAN_SECRET is true"