name: Workflow Run
on: 
  workflow_run:
    workflows: [events]
    types: [completed]
jobs:
    echo-string:
        runs-on: ubuntu-latest
        steps:
          - name: Echo a string
            run: echo "I was triggered by completion of the 'events' workflow."